name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:


    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YASWANTH_PANGULURI_ATS_10562 }}'
          channelId: live
          projectId: yaswanth-panguluri-ats-10562
